### ISSUE TITLE
Make About button more intuitive

### ISSUE THREAD

**Issue by ssokolow** [jplatte/caniuse.rs#1]
The heart on the button leading to the About page is a poor choice. It's so strongly associated with like/fave (or, secondarily, with donate or bookmark) that, when it failed to produce a tooltip, I didn't click it to figure out what it did until after I'd searched through the DOM inspector trying to identify its purpose by a CSS class or some other non-href, non-tooltip indicator.

I strongly recommend two things:

1. Consider following the rule of thumb I follow: Every icon without accompanying text must have a tooltip. (This is also an accessibility improvement, since screen readers can access tooltips.)
2. Use iconography built around a question mark instead, since that's secondarily associated with "About" via the primary association of "Help".

Perhaps a  "question mark in a circle" design like this FontAwesome glyph: https://fontawesome.com/icons/question-circle?style=solid

(You could even *use* that FontAwesome glyph. It's part of the CC-BY 4.0 licensed free subset and they offer an SVG version via the download button near the top of that page.)

**Comment by jplatte** [comment]
I'm not a fan of a question mark for the about button. Maybe there's another icon I could use, but adding a tooltip sounds like a good improvement either way.

**Comment by ssokolow** [comment]
From a pure aesthetic standpoint, I do think a question mark is uninspired, but that *is* what people have been trained to associate with that concept and Human-Computer Interaction research shows that the most important thing is consistency with previously learned symbology.

(Something I can't stand GNOME's decision-making on. A downward-pointing green arrow is already an overloaded concept. A floppy disk has become "the glyph for save" and lends itself well to extension, such as a cascade of floppy disks for "save all"... plus it lends itself to a red-blue color scheme which allows people with normal color vision to identify it even more readily.)

**Comment by jplatte** [comment]
I haven't chosen the heart icon because I think it looks better: I think it better communicates what can be found on that site. Afterall, it doesn't explain at all what the site does, how to use it or anything like that, but does link to this repository (=> like / fave) and liberapay (=> donate).

Maybe I should just rename the page. I don't know to what though.

**Comment by ssokolow** [comment]
Except that the directness of the association *matters*.

When I see that button, I expect it to do one of the following:

1. Provide some way to fave or bookmark the search that's typed into the box to the left
2. Take me to a Share/Like chooser like http://www.addtoany.com/
3. Prompt me to login

...none of which I want to do at that stage in our interaction. The heart icon has grown an implicit association with the kinds of non-idempotent actions which would map to an HTTP POST under the hood and, thus, I'm very wary of clicking on any heart icon without already knowing exactly what it will do.

**Comment by fan-tom** [comment]
I found `about` page only by directly typing its address in address bar, thought it is easter egg

**Comment by jplatte** [comment]
Okay, I guess that's enough evidence that it's confusing then. Will remove the heart icon and add an about link to the hamburger menu.

**Comment by jplatte** [comment]
I've thought more about this. Would you still find the button confusing if it opened only a popover with links (in the form of icons) to GitHub, sourcehut and liberapay?

**Comment by ssokolow** [comment]
If you intend to keep the heart, then no. Making it a popover would have no effect if users aren't clicking on it to begin with because the icon led them to an incorrect assumption of what the button does.

**Comment by janriemer** [comment]
My 2 cents :smile_cat: 
I fully agree with @ssokolow's points here.
Especially having separate buttons for Github, sourcehut, liberapay etc. **on the first page** will increase the chance of people actually visiting these sites, because they are **directly visible**. Also, tooltips don't work on mobile, so ¯\_(ツ)_/¯

**But**, I also have to say:
@jplatte Thank you very much for this really nice piece of technology. The color coding of the Rust versions is really intuitive and the search works like a charm! :sparkles: :kissing_heart:

**Comment by jplatte** [comment]
@janriemer Thank you for the feedback, it is really appreciated. I didn't commit to any specific change before because I wasn't 100% happy with any of the solutions that had come up but you just gave me an idea for a design that I am 100% happy with. I will put a small notification-like bar below the header that can be dismissed (and probably re-enabled from the hamburger menu). The about site will "only" be reachable from the hamburger menu.

Thank you for the kind words :relaxed:

**Comment by jplatte** [comment]
The heart button has been removed. I will add the bar later, but the issue described here has been fixed now.
